
package cl.bice.nominasenlinea.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenericBancaDigitalService", targetNamespace = "http://portal.ws.bice.cl/", wsdlLocation = "file:/C:/Users/Fibacache/Documents/por_fecha/20190423/WSDL_MavenGenerator_JaxWs_Axis1_Axis2/src/main/webapp/wsdl/NominasEnLinea.wsdl")
public class GenericBancaDigitalService
    extends Service
{

    private final static URL GENERICBANCADIGITALSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENERICBANCADIGITALSERVICE_EXCEPTION;
    private final static QName GENERICBANCADIGITALSERVICE_QNAME = new QName("http://portal.ws.bice.cl/", "GenericBancaDigitalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Fibacache/Documents/por_fecha/20190423/WSDL_MavenGenerator_JaxWs_Axis1_Axis2/src/main/webapp/wsdl/NominasEnLinea.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERICBANCADIGITALSERVICE_WSDL_LOCATION = url;
        GENERICBANCADIGITALSERVICE_EXCEPTION = e;
    }

    public GenericBancaDigitalService() {
        super(__getWsdlLocation(), GENERICBANCADIGITALSERVICE_QNAME);
    }

    public GenericBancaDigitalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERICBANCADIGITALSERVICE_QNAME, features);
    }

    public GenericBancaDigitalService(URL wsdlLocation) {
        super(wsdlLocation, GENERICBANCADIGITALSERVICE_QNAME);
    }

    public GenericBancaDigitalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERICBANCADIGITALSERVICE_QNAME, features);
    }

    public GenericBancaDigitalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenericBancaDigitalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenericBancaDigital
     */
    @WebEndpoint(name = "GenericBancaDigitalPort")
    public GenericBancaDigital getGenericBancaDigitalPort() {
        return super.getPort(new QName("http://portal.ws.bice.cl/", "GenericBancaDigitalPort"), GenericBancaDigital.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenericBancaDigital
     */
    @WebEndpoint(name = "GenericBancaDigitalPort")
    public GenericBancaDigital getGenericBancaDigitalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://portal.ws.bice.cl/", "GenericBancaDigitalPort"), GenericBancaDigital.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERICBANCADIGITALSERVICE_EXCEPTION!= null) {
            throw GENERICBANCADIGITALSERVICE_EXCEPTION;
        }
        return GENERICBANCADIGITALSERVICE_WSDL_LOCATION;
    }

}
