
package cl.bice.nominasenlinea.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenericBancaDigital", targetNamespace = "http://portal.ws.bice.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenericBancaDigital {


    /**
     * 
     * @param obtenerParametros
     * @return
     *     returns cl.bice.nominasenlinea.ws.ConsParametrosOut
     */
    @WebMethod(operationName = "Obtener_Parametros")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Obtener_Parametros", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ObtenerParametros")
    @ResponseWrapper(localName = "Obtener_ParametrosResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ObtenerParametrosResponse")
    public ConsParametrosOut obtenerParametros(
        @WebParam(name = "ObtenerParametros", targetNamespace = "")
        ConsParametrosIn obtenerParametros);

    /**
     * 
     * @param obtNomParametros
     * @return
     *     returns cl.bice.nominasenlinea.ws.ConsParametrosOut
     */
    @WebMethod(operationName = "Obtener_Nom_Parametros")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Obtener_Nom_Parametros", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ObtenerNomParametros")
    @ResponseWrapper(localName = "Obtener_Nom_ParametrosResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ObtenerNomParametrosResponse")
    public ConsParametrosOut obtenerNomParametros(
        @WebParam(name = "ObtNomParametros", targetNamespace = "")
        ConsNomParamIn obtNomParametros);

    /**
     * 
     * @param registrarNomLin
     * @return
     *     returns cl.bice.nominasenlinea.ws.RegNomOut
     */
    @WebMethod(operationName = "Registrar_Nom_Lin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Registrar_Nom_Lin", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.RegistrarNomLin")
    @ResponseWrapper(localName = "Registrar_Nom_LinResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.RegistrarNomLinResponse")
    public RegNomOut registrarNomLin(
        @WebParam(name = "RegistrarNomLin", targetNamespace = "")
        RegNomIn registrarNomLin);

    /**
     * 
     * @param obetenerMtoMaxNomLin
     * @return
     *     returns cl.bice.nominasenlinea.ws.ConsMtoMaxOut
     */
    @WebMethod(operationName = "Obtener_MtoMax_NomLin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Obtener_MtoMax_NomLin", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ObtenerMtoMaxNomLin")
    @ResponseWrapper(localName = "Obtener_MtoMax_NomLinResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ObtenerMtoMaxNomLinResponse")
    public ConsMtoMaxOut obtenerMtoMaxNomLin(
        @WebParam(name = "ObetenerMtoMaxNomLin", targetNamespace = "")
        ConsMtoMaxIn obetenerMtoMaxNomLin);

    /**
     * 
     * @param listarRegNomLin
     * @return
     *     returns cl.bice.nominasenlinea.ws.RegistrosNomLinOut
     */
    @WebMethod(operationName = "Listar_Reg_NomLin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Listar_Reg_NomLin", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ListarRegNomLin")
    @ResponseWrapper(localName = "Listar_Reg_NomLinResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ListarRegNomLinResponse")
    public RegistrosNomLinOut listarRegNomLin(
        @WebParam(name = "ListarRegNomLin", targetNamespace = "")
        RegistrosNomLinIn listarRegNomLin);

    /**
     * 
     * @param actCerrarNomLin
     * @return
     *     returns cl.bice.nominasenlinea.ws.ActCerrarNomOut
     */
    @WebMethod(operationName = "Act_Cerrar_NomLin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Act_Cerrar_NomLin", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ActCerrarNomLin")
    @ResponseWrapper(localName = "Act_Cerrar_NomLinResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ActCerrarNomLinResponse")
    public ActCerrarNomOut actCerrarNomLin(
        @WebParam(name = "ActCerrarNomLin", targetNamespace = "")
        ActCerrarNomIn actCerrarNomLin);

    /**
     * 
     * @param actEstadoNomLin
     * @return
     *     returns cl.bice.nominasenlinea.ws.ActEstadoNomOut
     */
    @WebMethod(operationName = "Act_Estado_NomLin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Act_Estado_NomLin", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ActEstadoNomLin")
    @ResponseWrapper(localName = "Act_Estado_NomLinResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ActEstadoNomLinResponse")
    public ActEstadoNomOut actEstadoNomLin(
        @WebParam(name = "ActEstadoNomLin", targetNamespace = "")
        ActEstadoNomIn actEstadoNomLin);

    /**
     * 
     * @param aprobarNomLinReversa
     * @return
     *     returns cl.bice.nominasenlinea.ws.RevAprobarNomLinOut
     */
    @WebMethod(operationName = "Aprobar_NomLin_Reversa")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Aprobar_NomLin_Reversa", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.AprobarNomLinReversa")
    @ResponseWrapper(localName = "Aprobar_NomLin_ReversaResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.AprobarNomLinReversaResponse")
    public RevAprobarNomLinOut aprobarNomLinReversa(
        @WebParam(name = "AprobarNomLinReversa", targetNamespace = "")
        RevAprobarNomLinIn aprobarNomLinReversa);

    /**
     * 
     * @param consNomCliente
     * @return
     *     returns cl.bice.nominasenlinea.ws.ConsNombreClienteOut
     */
    @WebMethod(operationName = "Cons_Nom_Cliente")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Cons_Nom_Cliente", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ConsNomCliente")
    @ResponseWrapper(localName = "Cons_Nom_ClienteResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ConsNomClienteResponse")
    public ConsNombreClienteOut consNomCliente(
        @WebParam(name = "ConsNomCliente", targetNamespace = "")
        ConsNombreClienteIn consNomCliente);

    /**
     * 
     * @param consCuentasNomLin
     * @return
     *     returns cl.bice.nominasenlinea.ws.ConsCuentasNomLinOut
     */
    @WebMethod(operationName = "Cons_Cuentas_NomLin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Cons_Cuentas_NomLin", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ConsCuentasNomLin")
    @ResponseWrapper(localName = "Cons_Cuentas_NomLinResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ConsCuentasNomLinResponse")
    public ConsCuentasNomLinOut consCuentasNomLin(
        @WebParam(name = "ConsCuentasNomLin", targetNamespace = "")
        ConsCuentasNomLinIn consCuentasNomLin);

    /**
     * 
     * @param regRestriccionMonto
     * @return
     *     returns cl.bice.nominasenlinea.ws.RegRestriccionMontoOut
     */
    @WebMethod(operationName = "Reg_Restriccion_Monto")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Reg_Restriccion_Monto", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.RegRestriccionMonto")
    @ResponseWrapper(localName = "Reg_Restriccion_MontoResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.RegRestriccionMontoResponse")
    public RegRestriccionMontoOut regRestriccionMonto(
        @WebParam(name = "RegRestriccionMonto", targetNamespace = "")
        RegRestriccionMontoIn regRestriccionMonto);

    /**
     * 
     * @param actRestriccionMonto
     * @return
     *     returns cl.bice.nominasenlinea.ws.ActRestriccionMontoOut
     */
    @WebMethod(operationName = "Act_Restriccion_Monto")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Act_Restriccion_Monto", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ActRestriccionMonto")
    @ResponseWrapper(localName = "Act_Restriccion_MontoResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ActRestriccionMontoResponse")
    public ActRestriccionMontoOut actRestriccionMonto(
        @WebParam(name = "ActRestriccionMonto", targetNamespace = "")
        ActRestriccionMontoIn actRestriccionMonto);

    /**
     * 
     * @param insSegFda
     * @return
     *     returns cl.bice.nominasenlinea.ws.InsertSegFdaOut
     */
    @WebMethod(operationName = "Ins_Seg_Fda")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Ins_Seg_Fda", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.InsSegFda")
    @ResponseWrapper(localName = "Ins_Seg_FdaResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.InsSegFdaResponse")
    public InsertSegFdaOut insSegFda(
        @WebParam(name = "InsSegFda", targetNamespace = "")
        InsertSegFdaIn insSegFda);

    /**
     * 
     * @param consRestMonto
     * @return
     *     returns cl.bice.nominasenlinea.ws.ConsRestriccionMontoOut
     */
    @WebMethod(operationName = "Cons_Rest_Monto")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Cons_Rest_Monto", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ConsRestMonto")
    @ResponseWrapper(localName = "Cons_Rest_MontoResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ConsRestMontoResponse")
    public ConsRestriccionMontoOut consRestMonto(
        @WebParam(name = "ConsRestMonto", targetNamespace = "")
        ConsRestriccionMontoIn consRestMonto);

    /**
     * 
     * @param consEnvioMail
     * @return
     *     returns cl.bice.nominasenlinea.ws.ConsEnvioMailOut
     */
    @WebMethod(operationName = "Cons_Envio_Mail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Cons_Envio_Mail", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ConsEnvioMail")
    @ResponseWrapper(localName = "Cons_Envio_MailResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ConsEnvioMailResponse")
    public ConsEnvioMailOut consEnvioMail(
        @WebParam(name = "ConsEnvioMail", targetNamespace = "")
        ConsEnvioMailIn consEnvioMail);

    /**
     * 
     * @param regEnvioMail
     * @return
     *     returns cl.bice.nominasenlinea.ws.RegEnvioMailOut
     */
    @WebMethod(operationName = "Reg_Envio_Mail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Reg_Envio_Mail", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.RegEnvioMail")
    @ResponseWrapper(localName = "Reg_Envio_MailResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.RegEnvioMailResponse")
    public RegEnvioMailOut regEnvioMail(
        @WebParam(name = "RegEnvioMail", targetNamespace = "")
        RegEnvioMailIn regEnvioMail);

    /**
     * 
     * @param actEnvioMail
     * @return
     *     returns cl.bice.nominasenlinea.ws.ActEnvioMailOut
     */
    @WebMethod(operationName = "Act_Envio_Mail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Act_Envio_Mail", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ActEnvioMail")
    @ResponseWrapper(localName = "Act_Envio_MailResponse", targetNamespace = "http://portal.ws.bice.cl/", className = "cl.bice.nominasenlinea.ws.ActEnvioMailResponse")
    public ActEnvioMailOut actEnvioMail(
        @WebParam(name = "ActEnvioMail", targetNamespace = "")
        ActEnvioMailIn actEnvioMail);

}
