
package cl.bice.nominas.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NominasPagosWs", targetNamespace = "http://ws.nominas.bice.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NominasPagosWs {


    /**
     * 
     * @param reversaNomina
     * @return
     *     returns cl.bice.nominas.ws.ReversaNominaOut
     */
    @WebMethod(operationName = "Reversa_Nomina")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Reversa_Nomina", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ReversaNomina")
    @ResponseWrapper(localName = "Reversa_NominaResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ReversaNominaResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Reversa_NominaRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Reversa_NominaResponse")
    public ReversaNominaOut reversaNomina(
        @WebParam(name = "reversaNomina", targetNamespace = "")
        ReversaNominaIn reversaNomina);

    /**
     * 
     * @param registraOperProg
     * @return
     *     returns cl.bice.nominas.ws.InsertaOpOut
     */
    @WebMethod(operationName = "Registra_Op")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Registra_Op", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.RegistraOp")
    @ResponseWrapper(localName = "Registra_OpResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.RegistraOpResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Registra_OpRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Registra_OpResponse")
    public InsertaOpOut registraOp(
        @WebParam(name = "registraOperProg", targetNamespace = "")
        InsertaOpIn registraOperProg);

    /**
     * 
     * @param consultaFirmaApo
     * @return
     *     returns cl.bice.nominas.ws.ConsultaApoOpOut
     */
    @WebMethod(operationName = "Consulta_Firma_Op")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Consulta_Firma_Op", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ConsultaFirmaOp")
    @ResponseWrapper(localName = "Consulta_Firma_OpResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ConsultaFirmaOpResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Consulta_Firma_OpRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Consulta_Firma_OpResponse")
    public ConsultaApoOpOut consultaFirmaOp(
        @WebParam(name = "consultaFirmaApo", targetNamespace = "")
        ConsultaApoOpIn consultaFirmaApo);

    /**
     * 
     * @param actualizaDetCamp
     * @return
     *     returns cl.bice.nominas.ws.ActualizaDetCampOut
     */
    @WebMethod(operationName = "Actualiza_Det_Camp")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Actualiza_Det_Camp", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ActualizaDetCamp")
    @ResponseWrapper(localName = "Actualiza_Det_CampResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ActualizaDetCampResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Actualiza_Det_CampRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Actualiza_Det_CampResponse")
    public ActualizaDetCampOut actualizaDetCamp(
        @WebParam(name = "actualizaDetCamp", targetNamespace = "")
        ActualizaDetCampIn actualizaDetCamp);

    /**
     * 
     * @param actualizaOp
     * @return
     *     returns cl.bice.nominas.ws.ActualizaOpOut
     */
    @WebMethod(operationName = "Actualiza_Oper_Prog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Actualiza_Oper_Prog", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ActualizaOperProg")
    @ResponseWrapper(localName = "Actualiza_Oper_ProgResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ActualizaOperProgResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Actualiza_Oper_ProgRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Actualiza_Oper_ProgResponse")
    public ActualizaOpOut actualizaOperProg(
        @WebParam(name = "actualizaOp", targetNamespace = "")
        ActualizaOpIn actualizaOp);

    /**
     * 
     * @param firmaApoderado
     * @return
     *     returns cl.bice.nominas.ws.RegistraApoOpOut
     */
    @WebMethod(operationName = "Registra_Firma_Op")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Registra_Firma_Op", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.RegistraFirmaOp")
    @ResponseWrapper(localName = "Registra_Firma_OpResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.RegistraFirmaOpResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Registra_Firma_OpRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Registra_Firma_OpResponse")
    public RegistraApoOpOut registraFirmaOp(
        @WebParam(name = "firmaApoderado", targetNamespace = "")
        RegistraApoOpIn firmaApoderado);

    /**
     * 
     * @param eliminafirmaApo
     * @return
     *     returns cl.bice.nominas.ws.EliminaApoOpOut
     */
    @WebMethod(operationName = "Elimina_Firma_Op")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Elimina_Firma_Op", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.EliminaFirmaOp")
    @ResponseWrapper(localName = "Elimina_Firma_OpResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.EliminaFirmaOpResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Elimina_Firma_OpRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Elimina_Firma_OpResponse")
    public EliminaApoOpOut eliminaFirmaOp(
        @WebParam(name = "eliminafirmaApo", targetNamespace = "")
        EliminaApoOpIn eliminafirmaApo);

    /**
     * 
     * @param actualizaNomina
     * @return
     *     returns cl.bice.nominas.ws.ActualizaNominaOut
     */
    @WebMethod(operationName = "Actualiza_Nomina")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Actualiza_Nomina", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ActualizaNomina")
    @ResponseWrapper(localName = "Actualiza_NominaResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ActualizaNominaResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Actualiza_NominaRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Actualiza_NominaResponse")
    public ActualizaNominaOut actualizaNomina(
        @WebParam(name = "actualizaNomina", targetNamespace = "")
        ActualizaNominaIn actualizaNomina);

    /**
     * 
     * @param insertaIOdata
     * @return
     *     returns cl.bice.nominas.ws.InsertaIOdataOut
     */
    @WebMethod(operationName = "Inserta_IOdata")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Inserta_IOdata", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.InsertaIOdata")
    @ResponseWrapper(localName = "Inserta_IOdataResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.InsertaIOdataResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Inserta_IOdataRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Inserta_IOdataResponse")
    public InsertaIOdataOut insertaIOdata(
        @WebParam(name = "insertaIOdata", targetNamespace = "")
        InsertaIOdataIn insertaIOdata);

    /**
     * 
     * @param consultaParam
     * @return
     *     returns cl.bice.nominas.ws.ConsultaParametrosOut
     */
    @WebMethod(operationName = "Consulta_Param_Nominas")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Consulta_Param_Nominas", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ConsultaParamNominas")
    @ResponseWrapper(localName = "Consulta_Param_NominasResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ConsultaParamNominasResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Consulta_Param_NominasRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Consulta_Param_NominasResponse")
    public ConsultaParametrosOut consultaParamNominas(
        @WebParam(name = "consultaParam", targetNamespace = "")
        ConsultaParametrosIn consultaParam);

    /**
     * 
     * @param consultaParamVal
     * @return
     *     returns cl.bice.nominas.ws.ConsultaParametrosOut
     */
    @WebMethod(operationName = "Consulta_Param_Validacion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Consulta_Param_Validacion", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ConsultaParamValidacion")
    @ResponseWrapper(localName = "Consulta_Param_ValidacionResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.ConsultaParamValidacionResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Consulta_Param_ValidacionRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Consulta_Param_ValidacionResponse")
    public ConsultaParametrosOut consultaParamValidacion(
        @WebParam(name = "consultaParamVal", targetNamespace = "")
        ConsultaParametrosIn consultaParamVal);

    /**
     * 
     * @param operaOnline
     * @return
     *     returns cl.bice.nominas.ws.OperaCargoOnlineOut
     */
    @WebMethod(operationName = "Opera_Online")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Opera_Online", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.OperaOnline")
    @ResponseWrapper(localName = "Opera_OnlineResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.OperaOnlineResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Opera_OnlineRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Opera_OnlineResponse")
    public OperaCargoOnlineOut operaOnline(
        @WebParam(name = "operaOnline", targetNamespace = "")
        OperaCargoOnlineIn operaOnline);

    /**
     * 
     * @param aplicaCargo
     * @return
     *     returns cl.bice.nominas.ws.CargoOnlineOut
     */
    @WebMethod(operationName = "Aplica_Cargo_Online")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Aplica_Cargo_Online", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.AplicaCargoOnline")
    @ResponseWrapper(localName = "Aplica_Cargo_OnlineResponse", targetNamespace = "http://ws.nominas.bice.cl/", className = "cl.bice.nominas.ws.AplicaCargoOnlineResponse")
    @Action(input = "http://ws.nominas.bice.cl/NominasPagosWs/Aplica_Cargo_OnlineRequest", output = "http://ws.nominas.bice.cl/NominasPagosWs/Aplica_Cargo_OnlineResponse")
    public CargoOnlineOut aplicaCargoOnline(
        @WebParam(name = "aplicaCargo", targetNamespace = "")
        ApliCargoOnlineIn aplicaCargo);

}
