
package cl.bice.nominas.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NominasPagosWsService", targetNamespace = "http://ws.nominas.bice.cl/", wsdlLocation = "file:/C:/Users/Luis%20Basso/AppData/Local/Temp/tempdir1799783382166937646.tmp/NominasPagosWsService_1.wsdl")
public class NominasPagosWsService
    extends Service
{

    private final static URL NOMINASPAGOSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOMINASPAGOSWSSERVICE_EXCEPTION;
    private final static QName NOMINASPAGOSWSSERVICE_QNAME = new QName("http://ws.nominas.bice.cl/", "NominasPagosWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Luis%20Basso/AppData/Local/Temp/tempdir1799783382166937646.tmp/NominasPagosWsService_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOMINASPAGOSWSSERVICE_WSDL_LOCATION = url;
        NOMINASPAGOSWSSERVICE_EXCEPTION = e;
    }

    public NominasPagosWsService() {
        super(__getWsdlLocation(), NOMINASPAGOSWSSERVICE_QNAME);
    }

    public NominasPagosWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOMINASPAGOSWSSERVICE_QNAME, features);
    }

    public NominasPagosWsService(URL wsdlLocation) {
        super(wsdlLocation, NOMINASPAGOSWSSERVICE_QNAME);
    }

    public NominasPagosWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOMINASPAGOSWSSERVICE_QNAME, features);
    }

    public NominasPagosWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NominasPagosWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NominasPagosWs
     */
    @WebEndpoint(name = "NominasPagosWsPort")
    public NominasPagosWs getNominasPagosWsPort() {
        return super.getPort(new QName("http://ws.nominas.bice.cl/", "NominasPagosWsPort"), NominasPagosWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NominasPagosWs
     */
    @WebEndpoint(name = "NominasPagosWsPort")
    public NominasPagosWs getNominasPagosWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.nominas.bice.cl/", "NominasPagosWsPort"), NominasPagosWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOMINASPAGOSWSSERVICE_EXCEPTION!= null) {
            throw NOMINASPAGOSWSSERVICE_EXCEPTION;
        }
        return NOMINASPAGOSWSSERVICE_WSDL_LOCATION;
    }

}
