
package cl.bice.genericoperprog.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenericOperProgWS", targetNamespace = "http://ws.operprog.bice.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenericOperProgWS {


    /**
     * 
     * @param firmaApoderado
     * @return
     *     returns cl.bice.genericoperprog.ws.RegistraApoOpOut
     */
    @WebMethod(operationName = "Registra_Firma_Op")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Registra_Firma_Op", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.RegistraFirmaOp")
    @ResponseWrapper(localName = "Registra_Firma_OpResponse", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.RegistraFirmaOpResponse")
    @Action(input = "http://ws.operprog.bice.cl/GenericOperProgWS/Registra_Firma_OpRequest", output = "http://ws.operprog.bice.cl/GenericOperProgWS/Registra_Firma_OpResponse")
    public RegistraApoOpOut registraFirmaOp(
        @WebParam(name = "firmaApoderado", targetNamespace = "")
        RegistraApoOpIn firmaApoderado);

    /**
     * 
     * @param consultaFirmaApo
     * @return
     *     returns cl.bice.genericoperprog.ws.ConsultaApoOpOut
     */
    @WebMethod(operationName = "Consulta_Firma_Op")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Consulta_Firma_Op", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ConsultaFirmaOp")
    @ResponseWrapper(localName = "Consulta_Firma_OpResponse", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ConsultaFirmaOpResponse")
    @Action(input = "http://ws.operprog.bice.cl/GenericOperProgWS/Consulta_Firma_OpRequest", output = "http://ws.operprog.bice.cl/GenericOperProgWS/Consulta_Firma_OpResponse")
    public ConsultaApoOpOut consultaFirmaOp(
        @WebParam(name = "consultaFirmaApo", targetNamespace = "")
        ConsultaApoOpIn consultaFirmaApo);

    /**
     * 
     * @param actualizaDetCamp
     * @return
     *     returns cl.bice.genericoperprog.ws.ActualizaDetCampOut
     */
    @WebMethod(operationName = "Actualiza_Det_Camp")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Actualiza_Det_Camp", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ActualizaDetCamp")
    @ResponseWrapper(localName = "Actualiza_Det_CampResponse", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ActualizaDetCampResponse")
    @Action(input = "http://ws.operprog.bice.cl/GenericOperProgWS/Actualiza_Det_CampRequest", output = "http://ws.operprog.bice.cl/GenericOperProgWS/Actualiza_Det_CampResponse")
    public ActualizaDetCampOut actualizaDetCamp(
        @WebParam(name = "actualizaDetCamp", targetNamespace = "")
        ActualizaDetCampIn actualizaDetCamp);

    /**
     * 
     * @param actualizaOp
     * @return
     *     returns cl.bice.genericoperprog.ws.ActualizaOpOut
     */
    @WebMethod(operationName = "Actualiza_Oper_Prog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Actualiza_Oper_Prog", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ActualizaOperProg")
    @ResponseWrapper(localName = "Actualiza_Oper_ProgResponse", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ActualizaOperProgResponse")
    @Action(input = "http://ws.operprog.bice.cl/GenericOperProgWS/Actualiza_Oper_ProgRequest", output = "http://ws.operprog.bice.cl/GenericOperProgWS/Actualiza_Oper_ProgResponse")
    public ActualizaOpOut actualizaOperProg(
        @WebParam(name = "actualizaOp", targetNamespace = "")
        ActualizaOpIn actualizaOp);

    /**
     * 
     * @param reversaNomina
     * @return
     *     returns cl.bice.genericoperprog.ws.ReversaNominaOut
     */
    @WebMethod(operationName = "Reversa_Nomina")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Reversa_Nomina", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ReversaNomina")
    @ResponseWrapper(localName = "Reversa_NominaResponse", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ReversaNominaResponse")
    @Action(input = "http://ws.operprog.bice.cl/GenericOperProgWS/Reversa_NominaRequest", output = "http://ws.operprog.bice.cl/GenericOperProgWS/Reversa_NominaResponse")
    public ReversaNominaOut reversaNomina(
        @WebParam(name = "reversaNomina", targetNamespace = "")
        ReversaNominaIn reversaNomina);

    /**
     * 
     * @param eliminafirmaApo
     * @return
     *     returns cl.bice.genericoperprog.ws.EliminaApoOpOut
     */
    @WebMethod(operationName = "Elimina_Firma_Op")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Elimina_Firma_Op", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.EliminaFirmaOp")
    @ResponseWrapper(localName = "Elimina_Firma_OpResponse", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.EliminaFirmaOpResponse")
    @Action(input = "http://ws.operprog.bice.cl/GenericOperProgWS/Elimina_Firma_OpRequest", output = "http://ws.operprog.bice.cl/GenericOperProgWS/Elimina_Firma_OpResponse")
    public EliminaApoOpOut eliminaFirmaOp(
        @WebParam(name = "eliminafirmaApo", targetNamespace = "")
        EliminaApoOpIn eliminafirmaApo);

    /**
     * 
     * @param registraOperProg
     * @return
     *     returns cl.bice.genericoperprog.ws.InsertaOpOut
     */
    @WebMethod(operationName = "Registra_Op")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Registra_Op", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.RegistraOp")
    @ResponseWrapper(localName = "Registra_OpResponse", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.RegistraOpResponse")
    @Action(input = "http://ws.operprog.bice.cl/GenericOperProgWS/Registra_OpRequest", output = "http://ws.operprog.bice.cl/GenericOperProgWS/Registra_OpResponse")
    public InsertaOpOut registraOp(
        @WebParam(name = "registraOperProg", targetNamespace = "")
        InsertaOpIn registraOperProg);

    /**
     * 
     * @param actualizaNomina
     * @return
     *     returns cl.bice.genericoperprog.ws.ActualizaNominaOut
     */
    @WebMethod(operationName = "Actualiza_Nomina")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Actualiza_Nomina", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ActualizaNomina")
    @ResponseWrapper(localName = "Actualiza_NominaResponse", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.ActualizaNominaResponse")
    @Action(input = "http://ws.operprog.bice.cl/GenericOperProgWS/Actualiza_NominaRequest", output = "http://ws.operprog.bice.cl/GenericOperProgWS/Actualiza_NominaResponse")
    public ActualizaNominaOut actualizaNomina(
        @WebParam(name = "actualizaNomina", targetNamespace = "")
        ActualizaNominaIn actualizaNomina);

    /**
     * 
     * @param insertaIOdata
     * @return
     *     returns cl.bice.genericoperprog.ws.InsertaIOdataOut
     */
    @WebMethod(operationName = "Inserta_IOdata")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Inserta_IOdata", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.InsertaIOdata")
    @ResponseWrapper(localName = "Inserta_IOdataResponse", targetNamespace = "http://ws.operprog.bice.cl/", className = "cl.bice.genericoperprog.ws.InsertaIOdataResponse")
    @Action(input = "http://ws.operprog.bice.cl/GenericOperProgWS/Inserta_IOdataRequest", output = "http://ws.operprog.bice.cl/GenericOperProgWS/Inserta_IOdataResponse")
    public InsertaIOdataOut insertaIOdata(
        @WebParam(name = "insertaIOdata", targetNamespace = "")
        InsertaIOdataIn insertaIOdata);

}
