
package cl.bice.genericoperprog.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenericOperProgWsService", targetNamespace = "http://ws.operprog.bice.cl/", wsdlLocation = "file:/C:/Users/Fibacache/Documents/por_fecha/20190423/WSDL_MavenGenerator_JaxWs_Axis1_Axis2/src/main/webapp/wsdl/GenericOperProgWsService.wsdl")
public class GenericOperProgWsService
    extends Service
{

    private final static URL GENERICOPERPROGWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENERICOPERPROGWSSERVICE_EXCEPTION;
    private final static QName GENERICOPERPROGWSSERVICE_QNAME = new QName("http://ws.operprog.bice.cl/", "GenericOperProgWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Fibacache/Documents/por_fecha/20190423/WSDL_MavenGenerator_JaxWs_Axis1_Axis2/src/main/webapp/wsdl/GenericOperProgWsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERICOPERPROGWSSERVICE_WSDL_LOCATION = url;
        GENERICOPERPROGWSSERVICE_EXCEPTION = e;
    }

    public GenericOperProgWsService() {
        super(__getWsdlLocation(), GENERICOPERPROGWSSERVICE_QNAME);
    }

    public GenericOperProgWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERICOPERPROGWSSERVICE_QNAME, features);
    }

    public GenericOperProgWsService(URL wsdlLocation) {
        super(wsdlLocation, GENERICOPERPROGWSSERVICE_QNAME);
    }

    public GenericOperProgWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERICOPERPROGWSSERVICE_QNAME, features);
    }

    public GenericOperProgWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenericOperProgWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenericOperProgWS
     */
    @WebEndpoint(name = "GenericOperProgWSPort")
    public GenericOperProgWS getGenericOperProgWSPort() {
        return super.getPort(new QName("http://ws.operprog.bice.cl/", "GenericOperProgWSPort"), GenericOperProgWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenericOperProgWS
     */
    @WebEndpoint(name = "GenericOperProgWSPort")
    public GenericOperProgWS getGenericOperProgWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.operprog.bice.cl/", "GenericOperProgWSPort"), GenericOperProgWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERICOPERPROGWSSERVICE_EXCEPTION!= null) {
            throw GENERICOPERPROGWSSERVICE_EXCEPTION;
        }
        return GENERICOPERPROGWSSERVICE_WSDL_LOCATION;
    }

}
