
package cl.bice.tef.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TefPort", targetNamespace = "http://www.bice.cl/tef/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TefPort {


    /**
     * 
     * @param tpag5500Request
     * @return
     *     returns cl.bice.tef.ws.Tpag5500ResponseType
     */
    @WebMethod(operationName = "Tpag5500")
    @WebResult(name = "Tpag5500Response", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5500Response")
    public Tpag5500ResponseType tpag5500(
        @WebParam(name = "Tpag5500Request", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5500Request")
        Tpag5500RequestType tpag5500Request);

    /**
     * 
     * @param reversarRequest
     * @return
     *     returns cl.bice.tef.ws.ReversarResponseType
     */
    @WebMethod(operationName = "Reversar")
    @WebResult(name = "ReversarResponse", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "ReversarResponse")
    public ReversarResponseType reversar(
        @WebParam(name = "ReversarRequest", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "ReversarRequest")
        ReversarRequestType reversarRequest);

    /**
     * 
     * @param tpag2000Request
     * @return
     *     returns cl.bice.tef.ws.Tpag2000ResponseType
     */
    @WebMethod(operationName = "Tpag2000")
    @WebResult(name = "Tpag2000Response", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag2000Response")
    public Tpag2000ResponseType tpag2000(
        @WebParam(name = "Tpag2000Request", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag2000Request")
        Tpag2000RequestType tpag2000Request);

    /**
     * 
     * @param tpag5110Request
     * @return
     *     returns cl.bice.tef.ws.Tpag5110ResponseType
     */
    @WebMethod(operationName = "Tpag5110")
    @WebResult(name = "Tpag5110Response", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5110Response")
    public Tpag5110ResponseType tpag5110(
        @WebParam(name = "Tpag5110Request", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5110Request")
        Tpag5110RequestType tpag5110Request);

    /**
     * 
     * @param tpag5510Request
     * @return
     *     returns cl.bice.tef.ws.Tpag5510ResponseType
     */
    @WebMethod(operationName = "Tpag5510")
    @WebResult(name = "Tpag5510Response", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5510Response")
    public Tpag5510ResponseType tpag5510(
        @WebParam(name = "Tpag5510Request", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5510Request")
        Tpag5510RequestType tpag5510Request);

    /**
     * 
     * @param tpag5520Request
     * @return
     *     returns cl.bice.tef.ws.Tpag5520ResponseType
     */
    @WebMethod(operationName = "Tpag5520")
    @WebResult(name = "Tpag5520Response", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5520Response")
    public Tpag5520ResponseType tpag5520(
        @WebParam(name = "Tpag5520Request", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5520Request")
        Tpag5520RequestType tpag5520Request);

    /**
     * 
     * @param tpag5100Request
     * @return
     *     returns cl.bice.tef.ws.Tpag5100ResponseType
     */
    @WebMethod(operationName = "Tpag5100")
    @WebResult(name = "Tpag5100Response", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5100Response")
    public Tpag5100ResponseType tpag5100(
        @WebParam(name = "Tpag5100Request", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5100Request")
        Tpag5100RequestType tpag5100Request);

    /**
     * 
     * @param tpag5300Request
     * @return
     *     returns cl.bice.tef.ws.Tpag5300ResponseType
     */
    @WebMethod(operationName = "Tpag5300")
    @WebResult(name = "Tpag5300Response", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5300Response")
    public Tpag5300ResponseType tpag5300(
        @WebParam(name = "Tpag5300Request", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5300Request")
        Tpag5300RequestType tpag5300Request);

    /**
     * 
     * @param tpag5310Request
     * @return
     *     returns cl.bice.tef.ws.Tpag5310ResponseType
     */
    @WebMethod(operationName = "Tpag5310")
    @WebResult(name = "Tpag5310Response", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5310Response")
    public Tpag5310ResponseType tpag5310(
        @WebParam(name = "Tpag5310Request", targetNamespace = "http://www.bice.cl/tef/schemas", partName = "Tpag5310Request")
        Tpag5310RequestType tpag5310Request);

}
