
package cl.bice.tef.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TefPortService", targetNamespace = "http://www.bice.cl/tef/wsdl", wsdlLocation = "file:/C:/Users/Fibacache/Documents/por_fecha/20190423/WSDL_MavenGenerator_JaxWs_Axis1_Axis2/src/main/webapp/wsdl/tef.wsdl")
public class TefPortService
    extends Service
{

    private final static URL TEFPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException TEFPORTSERVICE_EXCEPTION;
    private final static QName TEFPORTSERVICE_QNAME = new QName("http://www.bice.cl/tef/wsdl", "TefPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Fibacache/Documents/por_fecha/20190423/WSDL_MavenGenerator_JaxWs_Axis1_Axis2/src/main/webapp/wsdl/tef.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEFPORTSERVICE_WSDL_LOCATION = url;
        TEFPORTSERVICE_EXCEPTION = e;
    }

    public TefPortService() {
        super(__getWsdlLocation(), TEFPORTSERVICE_QNAME);
    }

    public TefPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEFPORTSERVICE_QNAME, features);
    }

    public TefPortService(URL wsdlLocation) {
        super(wsdlLocation, TEFPORTSERVICE_QNAME);
    }

    public TefPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEFPORTSERVICE_QNAME, features);
    }

    public TefPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TefPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TefPort
     */
    @WebEndpoint(name = "TefPortPort")
    public TefPort getTefPortPort() {
        return super.getPort(new QName("http://www.bice.cl/tef/wsdl", "TefPortPort"), TefPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TefPort
     */
    @WebEndpoint(name = "TefPortPort")
    public TefPort getTefPortPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.bice.cl/tef/wsdl", "TefPortPort"), TefPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEFPORTSERVICE_EXCEPTION!= null) {
            throw TEFPORTSERVICE_EXCEPTION;
        }
        return TEFPORTSERVICE_WSDL_LOCATION;
    }

}
