
package cl.bice.tel23300.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TEL23300", targetNamespace = "http://tel23300.ws.bice.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TEL23300 {


    /**
     * 
     * @param cuenta
     * @param moneda
     * @param canal
     * @return
     *     returns cl.bice.tel23300.ws.Tel23300Out
     */
    @WebMethod(operationName = "Execute")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Execute", targetNamespace = "http://tel23300.ws.bice.cl/", className = "cl.bice.tel23300.ws.Execute")
    @ResponseWrapper(localName = "ExecuteResponse", targetNamespace = "http://tel23300.ws.bice.cl/", className = "cl.bice.tel23300.ws.ExecuteResponse")
    public Tel23300Out execute(
        @WebParam(name = "CANAL", targetNamespace = "")
        String canal,
        @WebParam(name = "MONEDA", targetNamespace = "")
        String moneda,
        @WebParam(name = "CUENTA", targetNamespace = "")
        String cuenta);

}
