
package cl.bice.tel23300.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TEL23300Service", targetNamespace = "http://tel23300.ws.bice.cl/", wsdlLocation = "file:/C:/Users/Fibacache/Documents/por_fecha/20190423/WSDL_MavenGenerator_JaxWs_Axis1_Axis2/src/main/webapp/wsdl/TEL23300Service.wsdl")
public class TEL23300Service
    extends Service
{

    private final static URL TEL23300SERVICE_WSDL_LOCATION;
    private final static WebServiceException TEL23300SERVICE_EXCEPTION;
    private final static QName TEL23300SERVICE_QNAME = new QName("http://tel23300.ws.bice.cl/", "TEL23300Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Fibacache/Documents/por_fecha/20190423/WSDL_MavenGenerator_JaxWs_Axis1_Axis2/src/main/webapp/wsdl/TEL23300Service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEL23300SERVICE_WSDL_LOCATION = url;
        TEL23300SERVICE_EXCEPTION = e;
    }

    public TEL23300Service() {
        super(__getWsdlLocation(), TEL23300SERVICE_QNAME);
    }

    public TEL23300Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEL23300SERVICE_QNAME, features);
    }

    public TEL23300Service(URL wsdlLocation) {
        super(wsdlLocation, TEL23300SERVICE_QNAME);
    }

    public TEL23300Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEL23300SERVICE_QNAME, features);
    }

    public TEL23300Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TEL23300Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TEL23300
     */
    @WebEndpoint(name = "TEL23300Port")
    public TEL23300 getTEL23300Port() {
        return super.getPort(new QName("http://tel23300.ws.bice.cl/", "TEL23300Port"), TEL23300.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TEL23300
     */
    @WebEndpoint(name = "TEL23300Port")
    public TEL23300 getTEL23300Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://tel23300.ws.bice.cl/", "TEL23300Port"), TEL23300.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEL23300SERVICE_EXCEPTION!= null) {
            throw TEL23300SERVICE_EXCEPTION;
        }
        return TEL23300SERVICE_WSDL_LOCATION;
    }

}
