
package cl.bice.gfs.genericfinancialservice.ws;

import javax.xml.ws.WebFault;

import cl.bice.gfs.ws.GENERICFINANCIALSERVICEIN;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GENERICFINANCIALSERVICE_IN", targetNamespace = "http://www.bice.cl/wsdl")
public class FaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GENERICFINANCIALSERVICEIN faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FaultMessage(String message, GENERICFINANCIALSERVICEIN faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FaultMessage(String message, GENERICFINANCIALSERVICEIN faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cl.bice.wsdl.GENERICFINANCIALSERVICEIN
     */
    public GENERICFINANCIALSERVICEIN getFaultInfo() {
        return faultInfo;
    }

}
