
package cl.bice.gfs.genericfinancialservice.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenericFinancialService", targetNamespace = "http://oracle.com/sca/soapservice/PEI_CCA/GenericFinancialService/GenericFinancialService", wsdlLocation = "file:/C:/Users/Luis%20Basso/AppData/Local/Temp/tempdir2076691039808748387.tmp/GFS_1.wsdl")
public class GenericFinancialService_Service
    extends Service
{

    private final static URL GENERICFINANCIALSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENERICFINANCIALSERVICE_EXCEPTION;
    private final static QName GENERICFINANCIALSERVICE_QNAME = new QName("http://oracle.com/sca/soapservice/PEI_CCA/GenericFinancialService/GenericFinancialService", "GenericFinancialService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Luis%20Basso/AppData/Local/Temp/tempdir2076691039808748387.tmp/GFS_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERICFINANCIALSERVICE_WSDL_LOCATION = url;
        GENERICFINANCIALSERVICE_EXCEPTION = e;
    }

    public GenericFinancialService_Service() {
        super(__getWsdlLocation(), GENERICFINANCIALSERVICE_QNAME);
    }

    public GenericFinancialService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERICFINANCIALSERVICE_QNAME, features);
    }

    public GenericFinancialService_Service(URL wsdlLocation) {
        super(wsdlLocation, GENERICFINANCIALSERVICE_QNAME);
    }

    public GenericFinancialService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERICFINANCIALSERVICE_QNAME, features);
    }

    public GenericFinancialService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenericFinancialService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenericFinancialService
     */
    @WebEndpoint(name = "GenericFinancialService_pt")
    public GenericFinancialService getGenericFinancialServicePt() {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/PEI_CCA/GenericFinancialService/GenericFinancialService", "GenericFinancialService_pt"), GenericFinancialService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenericFinancialService
     */
    @WebEndpoint(name = "GenericFinancialService_pt")
    public GenericFinancialService getGenericFinancialServicePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://oracle.com/sca/soapservice/PEI_CCA/GenericFinancialService/GenericFinancialService", "GenericFinancialService_pt"), GenericFinancialService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERICFINANCIALSERVICE_EXCEPTION!= null) {
            throw GENERICFINANCIALSERVICE_EXCEPTION;
        }
        return GENERICFINANCIALSERVICE_WSDL_LOCATION;
    }

}
