
package cl.bice.gfs.genericfinancialservice.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import cl.bice.gfs.ws.GENERICFINANCIALSERVICEIN;
import cl.bice.gfs.ws.GENERICFINANCIALSERVICEOUT;
import cl.bice.gfs.ws.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenericFinancialService", targetNamespace = "http://oracle.com/sca/soapservice/PEI_CCA/GenericFinancialService/GenericFinancialService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenericFinancialService {


    /**
     * 
     * @param genericFinancialService
     * @return
     *     returns cl.bice.wsdl.GENERICFINANCIALSERVICEOUT
     * @throws FaultMessage
     */
    @WebMethod(operationName = "GenericFinancialService", action = "GenericFinancialService")
    @WebResult(name = "GENERICFINANCIALSERVICE_OUT", targetNamespace = "http://www.bice.cl/wsdl", partName = "GenericFinancialService")
    public GENERICFINANCIALSERVICEOUT genericFinancialService(
        @WebParam(name = "GENERICFINANCIALSERVICE_IN", targetNamespace = "http://www.bice.cl/wsdl", partName = "GenericFinancialService")
        GENERICFINANCIALSERVICEIN genericFinancialService)
        throws FaultMessage
    ;

}
